# Generated by Django 5.2.7 on 2025-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
