# Generated by Django 5.2.7 on 2025-12-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_fechacreacion_evento_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
    ]
