# Generated by Django 5.2.7 on 2025-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_fecha_fin_alter_evento_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
