# Generated by Django 5.2.7 on 2025-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
