# Generated by Django 5.2.7 on 2025-12-16 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_oracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupodeoracion',
            options={'ordering': ['nombre_grupo']},
        ),
        migrations.AddField(
            model_name='grupodeoracion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupodeoracion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grupodeoracion',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grupodeoracion',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
