# Generated by Django 5.2.7 on 2025-12-01 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('grupo_oracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('asunto', models.CharField(max_length=255, verbose_name='asunto')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado')], default='borrador', max_length=20, verbose_name='estado')),
                ('solo_newsletter', models.BooleanField(default=False, verbose_name='solo newsletter')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_masivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('grupo_oracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_masivos', to='grupo_oracion.grupodeoracion', verbose_name='grupo de oración')),
            ],
        ),
        migrations.CreateModel(
            name='DestinatarioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('enviado', models.BooleanField(default=False, verbose_name='enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_correos_masivos', to='contactos.contacto', verbose_name='contacto')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='correos.correomasivo', verbose_name='correo masivo')),
            ],
            options={
                'verbose_name': 'destinatario',
                'verbose_name_plural': 'destinatarios',
                'unique_together': {('correo', 'contacto')},
            },
        ),
    ]
