# Generated by Django 5.2.7 on 2025-12-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correomasivo',
            name='solo_newsletter',
        ),
        migrations.AlterField(
            model_name='correomasivo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='correomasivo',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='provincia'),
        ),
    ]
